version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: vnr_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: vnr_erp

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:

    build: .

    container_name: vnr_api

    depends_on:
      - postgres

    ports:
      - "3000:3000"

    environment:

      PORT: 3000

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: vnr_erp

      JWT_SECRET: secret_vnr_2026

    volumes:
      - .:/app
      - /app/node_modules

volumes:

  postgres_data: